import { SoftwareApplicationJsonLdProps } from "next-seo";

export const softwareApplications: SoftwareApplicationJsonLdProps[] = [
  {
    type: "WebApplication",
    name: "Mukesh Murugaiyan Portfolio",
    description:
      "Official portfolio web application of Mukesh Murugaiyan (TheMukesh), a Full Stack Developer showcasing web, mobile and desktop applications.",
    url: "https://themukesh.com",
    image: "https://themukesh.com/mukesh-mg.png",
    applicationCategory: "WebApplication",
    applicationSubCategory: "DeveloperPortfolio",
    applicationSuite: "Personal Portfolio",
    operatingSystem: "All",
    availableOnDevice: "Desktop, Mobile",
    permissions: "No special permissions required",
    softwareVersion: "1.0.0",
    releaseNotes: "Continuous updates with new projects and features",
    featureList: [
      "Developer portfolio",
      "Project showcase",
      "Resume download",
      "Contact form",
      "Freelance services",
      "Mobile & web app demos",
    ],
    countriesSupported: "Worldwide",
    author: {
      "@type": "Person",
      name: "Mukesh Murugaiyan",
    },
    publisher: {
      "@type": "Organization",
      name: "Mukesh Murugaiyan",
      url: "https://themukesh.com",
    },
    datePublished: "2020-01-01",
    dateModified: "2025-12-06",
    contentRating: "General",
  },
  {
    type: "MobileApplication",
    name: "Mukesh Murugaiyan",
    description:
      "High-performance Android applications built using React Native, Kotlin, and Node.js backend | by Full Stack Developer Mukesh Murugaiyan.",
    url: "https://themukesh.com",
    applicationCategory: "MobileApplication",
    operatingSystem: "Android",
    availableOnDevice: "Mobile",
    permissions: "No special permissions required",
    softwareVersion: "1.0.0",
    releaseNotes: "Continuous updates with new projects and features",
    featureList: [
      "Android app development",
      "High-performance mobile apps",
      "React Native apps",
    ],
    countriesSupported: "Worldwide",
    author: {
      "@type": "Person",
      name: "Mukesh Murugaiyan",
    },
    publisher: {
      "@type": "Organization",
      name: "Mukesh Murugaiyan",
      url: "https://themukesh.com",
    },
    datePublished: "2020-01-01",
    dateModified: "2025-12-06",
    contentRating: "General",
  },
  {
    type: "MobileApplication",
    name: "Mukesh Murugaiyan",
    description:
      "Modern and high-quality iOS applications developed using React Native and Node.js backend | by Full Stack Developer Mukesh Murugaiyan.",
    url: "https://themukesh.com",
    applicationCategory: "MobileApplication",
    operatingSystem: "iOS",
    availableOnDevice: "Mobile",
    permissions: "No special permissions required",
    softwareVersion: "1.0.0",
    releaseNotes: "Continuous updates with new projects and features",
    featureList: [
      "iOS app development",
      "High-performance mobile apps",
      "React Native apps",
    ],
    countriesSupported: "Worldwide",
    author: {
      "@type": "Person",
      name: "Mukesh Murugaiyan",
    },
    publisher: {
      "@type": "Organization",
      name: "Mukesh Murugaiyan",
      url: "https://themukesh.com",
    },
    datePublished: "2020-01-01",
    dateModified: "2025-12-06",
    contentRating: "General",
  },
  {
    type: "DesktopEnhancementApplication",
    name: "Mukesh Murugaiyan",
    description:
      "High-quality desktop applications built using Electron.js and Node.js backend | by Full Stack Developer Mukesh Murugaiyan.",
    url: "https://themukesh.com",
    applicationCategory: "DesktopEnhancementApplication",
    operatingSystem: "Windows, macOS, Linux",
    availableOnDevice: "Desktop",
    permissions: "No special permissions required",
    softwareVersion: "1.0.0",
    releaseNotes: "Continuous updates with new projects and features",
    featureList: [
      "Desktop app development",
      "Electron.js apps",
      "Cross-platform desktop applications",
    ],
    countriesSupported: "Worldwide",
    author: {
      "@type": "Person",
      name: "Mukesh Murugaiyan",
    },
    publisher: {
      "@type": "Organization",
      name: "Mukesh Murugaiyan",
      url: "https://themukesh.com",
    },
    datePublished: "2020-01-01",
    dateModified: "2025-12-06",
    contentRating: "General",
  },
  {
    type: "WebApplication",
    name: "CSS Grid Generator",
    applicationCategory: "DeveloperTool",
    operatingSystem: "All",
    description:
      "Visual CSS Grid layout generator tool built by Mukesh Murugaiyan for frontend developers.",
    url: "https://themukesh.com/tools/css-grid-generator",
    author: {
      "@type": "Person",
      name: "Mukesh Murugaiyan",
    },
  },
];
